# Generated by Django 4.1.5 on 2023-01-28 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_productclass_productoptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productclass',
            name='name',
            field=models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.CASCADE, to='catalogue.productoptions'),
        ),
    ]
