# Generated by Django 4.1.6 on 2023-03-06 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0006_delete_customuser'),
        ('catalogue', '0004_product_partner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_products', to='partner.partners'),
        ),
    ]
