# Generated by Django 4.1.6 on 2023-03-08 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0007_alter_partners_user'),
        ('catalogue', '0005_alter_product_partner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='partner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partner_products', to='partner.partners'),
        ),
    ]
