# Generated by Django 4.1.6 on 2023-02-08 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partners',
            options={'verbose_name': 'Partners', 'verbose_name_plural': 'Partners'},
        ),
        migrations.AddField(
            model_name='partners',
            name='phone',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
