# Generated by Django 4.1.6 on 2023-02-12 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0002_alter_partners_options_partners_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PartnerAddress',
        ),
    ]
