# Generated by Django 4.1.6 on 2023-02-13 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0003_delete_partneraddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='partners',
            name='address',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
