# Generated by Django 4.1.6 on 2023-02-28 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0005_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
